# Generated by Django 3.2 on 2022-03-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_job_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('acc', 'Accepted'), ('pen', 'Pending'), ('app', 'Applied')], default='app', max_length=3),
        ),
    ]
