# Generated by Django 3.2 on 2022-03-10 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_alter_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='about',
            field=models.TextField(blank=True, help_text='Say something about yourself, your love to hear you, briefly describe yourself, interests etc', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='bachelor_degree',
            field=models.CharField(default=1, help_text="Name of Field in which you have passed bachelors - Leave blank if you don't have bachelors degree", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of working experience'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='previous_company',
            field=models.CharField(blank=True, help_text='Leave blank if not', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='company/candidates/files/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.job'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
