# Generated by Django 3.2 on 2022-03-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_company',
            field=models.BooleanField(default=True, help_text='This account belongs to Company'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_completed',
            field=models.BooleanField(default=True, help_text='Is user fully fully identified to access application'),
        ),
    ]
