# Generated by Django 3.2 on 2022-03-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220309_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_company',
            field=models.BooleanField(default=False, help_text='This account belongs to Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Is user fully fully identified to access application'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False, help_text='This account belongs to customer'),
        ),
    ]
